### ISSUE TITLE
Please support more than 8 drivers

### ISSUE THREAD

**Issue by ariendj** [be1/qspeakers#3]
Hi be1,
I only found out about qspeakers recently and I really like it. So far I've been using a really ancient WinISD version under Wine and while it does work, I'm getting tired of both WinISD and Wine. I have been looking for something that runs on Linux natively and is more pleasing to the eye. qspeakers looks really nice and I like the fact that it is native to Linux and actively maintained.

While browsing diyaudio.com this evening I wanted to simulate a line array with the Visaton FRS5X. I'd like to sim a line array of those drivers concerning closed box volume (and potentially max SPL as defined by maximun excursion and the drivers power handling). Unfortunately, qspeakers does not simulate more than 8 drivers in one enclosure.

Could you increase the maximum number of drivers to something higher, like 64 or 128? That would help me with big enclosures full of tiny speakers :)

Thanks and all the best,
ariendj

**Comment by be1** [comment]
@ariendj sure, I will do it in a few days and publish a new version.

**Comment by be1** [comment]
changes in e02990ad451c22fede11a1a6e47657357c1537ff closes this bug.
