### ISSUE TITLE
How to generate frequency response of mobile devices

### ISSUE THREAD

**Issue by zuowanbushiwo** [be1/qspeakers#6]
Dear Sir 
this is a really cool project，I am an AI  software engineer. My recent work requires knowledge of acoustics and structure, but I have never been exposed to it before. 
I need to generate a lot of mobile device impulse responses to generate data and then train the AI model. As described in the second section of the Appendix.
I wonder if your program can generate some frequency curves for devices like Huawei Mate, iPhone , Samsung and smartspeaker and laptop?

[Device playback augmentation with echo cancellation for keyword spotting.pdf](https://github.com/user-attachments/files/15898988/Device.playback.augmentation.with.echo.cancellation.for.keyword.spotting.pdf)

Thanks!

**Comment by be1** [comment]
Dear Sir,
No, QSpeakers cannot do this. QSpeakers only predict bass frequency response of enclosures with large speakers.

But you can measure your mobile devices response curve by playing a swipe sinewave throught them from 20Hz to 20000Hz and capture the device response with a flat response microphone. Using swipe sinewave is equivalent to using impulsion. Check the [QLoud](https://github.com/molke-productions/qloud)  project for this, maybe this an help.

**Comment by zuowanbushiwo** [comment]
Dear @be1 

Thank you very much for your reply, it is very helpful to me. I am not familiar with the field of acoustics and structures, and I would like to ask you one more question: Do I need to measure in an anechoic chamber? From my limited knowledge, if I do not measure in an anechoic chamber, there will be interference from the impulse response of the house. But if I use an anechoic chamber, it will be too difficult to do. And what is a flat response microphone? Is it a calibration microphone? Can I buy it?

thanks！

**Comment by be1** [comment]
Yes, ideally, in an anechoic chamber. Do not use a calibration microphone, use a measurement microphone.
- The [cheapest one](https://www.thomann.de/intl/behringer_ecm_8000.htm) (I have this model)
- The [best seller](https://www.thomann.de/intl/beyerdynamic_mm_1_2023.htm)
- Among [others]( https://www.thomann.de/intl/cat_GK_mime.html)

**Comment by zuowanbushiwo** [comment]
Hi @be1 
Thank you very much for your kindness.
May I ask you another question: Do you know of any open source loudspeaker IR datasets (especially for portable devices like mobile phones and laptops)? I have only found [IR datasets](http://micirp.blogspot.com/p/about-micirp.html) for microphones .

**Comment by be1** [comment]
Sorry, I don't know. There are room impulse responses over the web, but I don't know about mobile devices loudspeakers (output), or microphones (input) IR.

**Comment by zuowanbushiwo** [comment]
thanks
best
